export const deployFiles = Object.freeze([
  'index.html',
  'app-icon.svg',
  'manifest.webmanifest',
  'service-worker.js',
  'style.css',
  'access.css',
  'login.css',
  'login-screen.css',
  'employee-calendar.css',
  'employee-layout.css',
  'time-off-ui.css',
  'notification-center.css',
  'announcement-center.css',
  'environment.css',
  'environment-config.js',
  'postgres-api-client.js',
  'postgres-offline.js',
  'postgres-cloud.js',
  'google-sheets-config.js',
  'state-store.js',
  'account-security.js',
  'dom-safety.js',
  'current-user-ui.js',
  'notification-navigation.js',
  'app.js',
  'access.js',
  'employee-work.js',
  'boss-hours.js',
  'management-actions.js',
  'login.js',
  'cloud-sync.js',
  'google-sheets-cloud.js',
  'enhancements.js',
  'pwa.js',
  'employee-layout.js',
  'time-off-ui.js',
  'notification-center.js',
  'announcement-center.js',
  '_headers',
  '_redirects'
]);

export const sourceScripts = Object.freeze(
  deployFiles.filter(file => file.endsWith('.js'))
);
